blimp_params:
  ros__parameters:
    mass: 4.620
    inertia:
      xx: 7.477239
      xy: 0.0
      xz: 0.0
      yy: 7.477239
      yz: 0.0
      zz: 2.871145
    rotor_configuration:
      '0': {angle: 1.57079, arm_length: 0.21, rotor_force_constant: 9.9865e-06,
            rotor_moment_constant: 1.6e-2, direction:  1.0}
      '1': {angle:-1.57079, arm_length: 0.21, rotor_force_constant: 9.9865e-06,
            rotor_moment_constant: 1.6e-2, direction: -1.0}
      '2': {angle: 3.14159, arm_length: 0.21, rotor_force_constant: 9.9865e-06,
            rotor_moment_constant: 1.6e-2, direction:  1.0}
      '3': {angle:-1.57079, arm_length: 0.21, rotor_force_constant: 9.9865e-06,
            rotor_moment_constant: 1.6e-2, direction:  1.0}
