controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    stick_joint_position_controller:
      type: position_controllers/JointPositionController

    botfin_joint_position_controller:
      type: position_controllers/JointPositionController

    topfin_joint_position_controller:
      type: position_controllers/JointPositionController

    leftfin_joint_position_controller:
      type: position_controllers/JointPositionController

    rightfin_joint_position_controller:
      type: position_controllers/JointPositionController

# Individual controller configurations
joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_stick_joint
      - bot_rud_part1_bot_rud_joint_link_joint
      - top_rud_part1_top_rud_joint_link_joint
      - left_elv_part1_left_elv_joint_link_joint
      - right_elv_part1_right_elv_joint_link_joint
    interfaces:
      - position
      - velocity

stick_joint_position_controller:
  ros__parameters:
    joints:
      - base_stick_joint
    interface_name: position

botfin_joint_position_controller:
  ros__parameters:
    joints:
      - bot_rud_part1_bot_rud_joint_link_joint
    interface_name: position

topfin_joint_position_controller:
  ros__parameters:
    joints:
      - top_rud_part1_top_rud_joint_link_joint
    interface_name: position

leftfin_joint_position_controller:
  ros__parameters:
    joints:
      - left_elv_part1_left_elv_joint_link_joint
    interface_name: position

rightfin_joint_position_controller:
  ros__parameters:
    joints:
      - right_elv_part1_right_elv_joint_link_joint
    interface_name: position