# Lee position controller parameters - Updated for ROS2/PX4 integration
# Note: Will be replaced with PX4 controllers in later migration
lee_position_controller:
  ros__parameters:
    position_gain: {x: 4.0, y: 4.0, z: 4.0}
    velocity_gain: {x: 2.7, y: 2.7, z: 2.7}
    attitude_gain: {x: 1.0, y: 1.0, z: 0.035}
    angular_rate_gain: {x: 0.22, y: 0.22, z: 0.01}
    
    # Additional parameters for ROS2
    mass: 4.620
    control_frequency: 100.0
    
    # PX4 transition parameters (for future migration)
    px4_transition:
      enable_px4_mode: false  # Set to true when migrating to PX4
      px4_topic_namespace: "/fmu/in"